# Generated by Django 4.2.3 on 2023-07-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0002_alter_watchlist_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
