# Generated by Django 5.0 on 2023-12-09 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies', '0003_audience_review_slug_alter_audience_review_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(upload_to='movies/qrcode')),
                ('theater', models.CharField(max_length=20)),
                ('seats', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('screen', models.CharField(max_length=2)),
                ('booking_id', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
