# Generated by Django 5.0 on 2023-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
