# Generated by Django 4.2.3 on 2023-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinematographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/cinematographer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/director')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/writer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
